name: Build

on:
    # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
    push:
        branches: [ main ]
    # Trigger the workflow on any pull request
    pull_request:

jobs:
    # Prepare environment and build packages
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Sources
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                filter: tree:0

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.x"
                  cache: true
                  cache-dependency-path: '**/packages.lock.json'

            - name: Restore and Build
              run: |
                    dotnet restore --locked-mode
                    dotnet tool restore
                    dotnet build -c Release

            - name: Pack Thunderstore
              run: dotnet build -c Release -t:PackThunderstore

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: "./artifacts/tspublish/build/*.zip"
